#ifndef CONSTANTS_H
#define CONSTANTS_H

#define QUERY 0;
#define STANDARD_QUERY 0;
#define NOT_AUTHORITATIVE 0;
#define NOT_TRUNCATED 0;
#define RECURSION_DESIRED 1;
#define RECURSION_NOT_AVAILABLE 0;
#define NO_ERRORS 0;
#define ONE_QUESTION 1;
#define NO_RESOURCE_RECORDS_IN_ANSWER 0;
#define NO_RESOURCE_RECORDS_IN_AUTHORITY 0;
#define NO_RESOURCE_RECORDS_IN_ADDITIONAL 0;

#endif
